packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalog:
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.0.0
  '@vueuse/shared': ^14.0.0
  vue: ^3.5.24
  vue-tsc: ^3.1.4
catalogs:
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    bumpp: ^10.3.1
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    tsdown: ^0.16.0
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.2.1
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.7
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.10.0
  conflicts_types_h24_10_1:
    '@types/node': ^24.10.1
  conflicts_cli_t5_9_3:
    typescript: ~5.9.3
  conflicts_cli_h7_2_4:
    vite: ^7.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
